name: OWASP Dependency Check

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Baixar OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.2.2/dependency-check-12.2.2-release.zip
          unzip dependency-check-12.2.2-release.zip

      - name: Executar análise
        run: |
          ./dependency-check/bin/dependency-check.sh \
          --project "while-language" \
          --scan "." \
          --format "HTML" \
          --out "reports" \
          --nvdApiDelay 5000

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports