name: OWASP Dependency Check

on:
  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Criar diretórios
        run: |
          mkdir -p reports
          mkdir -p odc-data

      - name: Executar OWASP Dependency Check
        run: |
          docker run --rm \
            -u root \
            -v ${{ github.workspace }}:/src \
            -v ${{ github.workspace }}/odc-data:/usr/share/dependency-check/data \
            owasp/dependency-check:latest \
            --scan /src \
            --format HTML \
            --format JSON \
            --out /src/reports \
            --disableYarnAudit

      - name: Upload do relatório
        uses: actions/upload-artifact@v7
        with:
          name: dependency-check-report
          path: reports