name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache ANTLR
        uses: actions/cache@v4
        with:
          path: lib/
          key: ${{ runner.os }}-antlr-4.13.1

      - name: Permissão no script
        run: chmod +x compilar.sh

      - name: Compilar (detecta deprecated)
        run: ./compilar.sh

      - name: Verificar classes compiladas
        run: |
          echo "=== BIN ==="
          find bin

      - name: Verificar JAR
        run: |
          echo "=== JAR ==="
          jar tf while.jar

      - name: Baixar Checkstyle
        run: |
          wget -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.17.0/checkstyle-10.17.0-all.jar

      - name: Verificar padrão de codificação
        run: |
          JAVA_FILES=$(find src/plp/enquanto -type f -name "*.java" ! -path "*/parser/*")

          java -jar checkstyle-10.17.0-all.jar \
            -c config/checkstyle.xml \
            $JAVA_FILES

      - name: Baixar PMD
        run: |
          wget -q https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.15.0/pmd-dist-7.15.0-bin.zip
          unzip -q pmd-dist-7.15.0-bin.zip

      - name: Detectar código duplicado (CPD)
        run: |
          ./pmd-bin-7.15.0/bin/pmd cpd \
            --dir src/plp/enquanto \
            --exclude ".*parser.*" \
            --language java \
            --minimum-tokens 30 \
            --fail-on-violation

      - name: Baixar SpotBugs
        run: |
          wget -q https://github.com/spotbugs/spotbugs/releases/download/4.8.6/spotbugs-4.8.6.tgz
          tar -xzf spotbugs-4.8.6.tgz

      - name: Análise com SpotBugs
        run: |
          chmod +x ./spotbugs-4.8.6/bin/spotbugs
          ./spotbugs-4.8.6/bin/spotbugs \
            -textui \
            -effort:max \
            -low \
            bin

      - name: Executar teste
        run: |
          find ./bin -name "Principal.class"
