name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache ANTLR
        uses: actions/cache@v4
        with:
          path: lib/
          key: ${{ runner.os }}-antlr-4.13.1

      - name: Permissão no script
        run: chmod +x compilar.sh

      - name: Compilar (detecta deprecated)
        run: ./compilar.sh

      - name: Baixar SpotBugs
        run: |
          wget -q https://github.com/spotbugs/spotbugs/releases/download/4.8.6/spotbugs-4.8.6.tgz
          tar -xzf spotbugs-4.8.6.tgz

      - name: Análise com SpotBugs
        run: |
          chmod +x ./spotbugs-4.8.6/bin/spotbugs
          ./spotbugs-4.8.6/bin/spotbugs \
            -textui \
            -effort:max \
            -low \
            bin

      - name: Executar teste
        run: |
          java -cp "bin:lib/antlr-runtime-4.13.1.jar" plp.enquanto.Principal teste.while